<?php

/**
 * This is the model base class for the table "snack".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Snack".
 *
 * Columns in table "snack" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idsnack
 * @property string $titulo
 * @property string $imagem
 * @property string $texto
 * @property string $ativo
 *
 */
abstract class BaseSnack extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'snack';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Snack|Snacks', $n);
	}

	public static function representingColumn() {
		return array('titulo');
	}

	public function rules() {
		return array(
			array('titulo', 'length', 'max'=>100),
			array('imagem', 'length', 'max'=>140),
			array('ativo', 'length', 'max'=>1),
			array('texto', 'safe'),
			array('titulo, imagem, texto, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idsnack, titulo, imagem, texto, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idsnack' => Yii::t('app', 'Idsnack'),
			'titulo' => Yii::t('app', 'Titulo'),
			'imagem' => Yii::t('app', 'Imagem'),
			'texto' => Yii::t('app', 'Texto'),
			'ativo' => Yii::t('app', 'Ativo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idsnack', $this->idsnack);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('texto', $this->texto, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}