<?php

/**
 * This is the model base class for the table "gallery_photo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GalleryPhoto".
 *
 * Columns in table "gallery_photo" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $gallery_id
 * @property integer $rank
 * @property string $name
 * @property string $description
 * @property string $file_name
 * @property string $activated
 *
 */
abstract class BaseGalleryPhoto extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gallery_photo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GalleryPhoto|GalleryPhotos', $n);
	}

	public static function representingColumn() {
		return array('activated');
	}

	public function rules() {
		return array(
			array('gallery_id, rank', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>512),
			array('file_name', 'length', 'max'=>128),
			array('activated', 'length', 'max'=>1),
			array('description', 'safe'),
			array('gallery_id, rank, name, description, file_name, activated', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, gallery_id, rank, name, description, file_name, activated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'gallery_id' => Yii::t('app', 'Gallery'),
			'rank' => Yii::t('app', 'Rank'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'file_name' => Yii::t('app', 'File Name'),
			'activated' => Yii::t('app', 'Activated'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('gallery_id', $this->gallery_id);
		$criteria->compare('rank', $this->rank);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('file_name', $this->file_name, true);
		$criteria->compare('activated', $this->activated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}