<?php

/**
 * This is the model base class for the table "produto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Produto".
 *
 * Columns in table "produto" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idproduto
 * @property string $nome
 * @property string $subtitulo
 * @property string $imagem
 * @property string $titulo
 * @property string $texto
 * @property string $ativo
 *
 */
abstract class BaseProduto extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'produto';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Produto|Produtos', $n);
	}

	public static function representingColumn() {
		return array('nome');
	}

	public function rules() {
		return array(
			array('nome, subtitulo, titulo', 'length', 'max'=>100),
			array('imagem', 'length', 'max'=>140),
			array('ativo', 'length', 'max'=>1),
			array('texto', 'safe'),
			array('nome, subtitulo, imagem, titulo, texto, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idproduto, nome, subtitulo, imagem, titulo, texto, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idproduto' => Yii::t('app', 'Idproduto'),
			'nome' => Yii::t('app', 'Nome'),
			'subtitulo' => Yii::t('app', 'Subtitulo'),
			'imagem' => Yii::t('app', 'Imagem'),
			'titulo' => Yii::t('app', 'Titulo'),
			'texto' => Yii::t('app', 'Texto'),
			'ativo' => Yii::t('app', 'Ativo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idproduto', $this->idproduto);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('subtitulo', $this->subtitulo, true);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('texto', $this->texto, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}