<?php

/**
 * This is the model base class for the table "destaque".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Destaque".
 *
 * Columns in table "destaque" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $iddestaque
 * @property string $titulo
 * @property string $imagem
 * @property string $link
 * @property string $ativo
 *
 */
abstract class BaseDestaque extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'destaque';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Destaque|Destaques', $n);
	}

	public static function representingColumn() {
		return array('titulo');
	}

	public function rules() {
		return array(
			array('titulo, link', 'length', 'max'=>100),
			array('imagem', 'length', 'max'=>140),
			array('ativo', 'length', 'max'=>1),
			array('titulo, imagem, link, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('iddestaque, titulo, imagem, link, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'iddestaque' => Yii::t('app', 'Iddestaque'),
			'titulo' => Yii::t('app', 'Titulo'),
			'imagem' => Yii::t('app', 'Imagem'),
			'link' => Yii::t('app', 'Link'),
			'ativo' => Yii::t('app', 'Ativo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('iddestaque', $this->iddestaque);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}