<?php

/**
 * This is the model base class for the table "banner".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Banner".
 *
 * Columns in table "banner" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idbanner
 * @property string $titulo
 * @property string $imagem
 * @property string $imagem_responsiva1
 * @property string $imagem_responsiva2
 * @property string $botao
 * @property string $link
 * @property string $externo
 * @property string $ativo
 *
 */
abstract class BaseBanner extends GxActiveRecord {
	
    
    public $imagem_delete;
	    
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'banner';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Banner|Banners', $n);
	}

	public static function representingColumn() {
		return array('titulo');
	}

	public function rules() {
		return array(
			array('titulo, botao, link', 'length', 'max'=>100),
			array('imagem', 'length', 'max'=>120),
			array('imagem_responsiva1, imagem_responsiva2', 'length', 'max'=>140),
			array('externo, ativo', 'length', 'max'=>1),
			array('imagem', 'file', 'types'=>'jpg,png', 'allowEmpty'=>true),
			array('imagem_delete', 'length', 'max'=>1),
			array('titulo, imagem, imagem_responsiva1, imagem_responsiva2, botao, link, externo, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idbanner, titulo, imagem, imagem_responsiva1, imagem_responsiva2, botao, link, externo, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idbanner' => Yii::t('app', 'Idbanner'),
			'titulo' => Yii::t('app', 'Titulo'),
			'imagem' => Yii::t('app', 'Imagem'),
			'imagem_responsiva1' => Yii::t('app', 'Imagem Responsiva1'),
			'imagem_responsiva2' => Yii::t('app', 'Imagem Responsiva2'),
			'botao' => Yii::t('app', 'Botao'),
			'link' => Yii::t('app', 'Link'),
			'externo' => Yii::t('app', 'Externo'),
			'ativo' => Yii::t('app', 'Ativo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idbanner', $this->idbanner);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('imagem_responsiva1', $this->imagem_responsiva1, true);
		$criteria->compare('imagem_responsiva2', $this->imagem_responsiva2, true);
		$criteria->compare('botao', $this->botao, true);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('externo', $this->externo, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}